dubbo:
    application:
      name: buckeyetrade-consumer
    registry:
      address: zookeeper://47.90.249.49:2181
    consumer:
      timeout: 3000
      check: false
server:
  port: 8079
spring:
  servlet:
    multipart:
      max-file-size: 2MB

