dubbo:
    application:
      name: buckeyetrade-consumer
    registry:
      address: zookeeper://47.90.245.180:2181
    consumer:
      timeout: 3000
server:
  port: 8079
spring:
  servlet:
    multipart:
      max-file-size: 2MB

