spring:
  datasource:
    url: jdbc:mysql://47.90.250.152/message?serverTimezone=UTC
    username: root
    password: lwl213615hqy
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
mybatis:
  mapper-locations: classpath:com/hygg/mapper/*.xml
  type-aliases-package: com.hygg.entity
  configuration:
    mapUnderscoreToCamelCase: true
fileUpload:
  post:
    resourceLocation: /usr/local/pic/posts/
  avatar:
    resourceLocation: /usr/local/pic/avatars/
server:
  port: 8084
myServer:
  address: http://47.90.250.152
dubbo:
  application:
    name: message-provider
  registry:
    protocol: zookeeper
    address: 47.90.249.49:2181,47.90.245.180:2181,47.90.250.152:2181
    simplified: true
    file: /dubbo-server/dubbo-registry-message.properties
  protocol:
    name: dubbo
    port: 20883
  provider:
    timeout: 3000
    retries: 2
    version: 0.1
    dynamic: true
  consumer:
    check: false



