package com.hygg.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table follow
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Follow  implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.follow_id
     *
     * @mbggenerated
     */
    private Integer followId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.follower_id
     *
     * @mbggenerated
     */
    private Integer followerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.followed_user_id
     *
     * @mbggenerated
     */
    private Integer followedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.follow_id
     *
     * @return the value of follow.follow_id
     *
     * @mbggenerated
     */
    public Integer getFollowId() {
        return followId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.follow_id
     *
     * @param followId the value for follow.follow_id
     *
     * @mbggenerated
     */
    public void setFollowId(Integer followId) {
        this.followId = followId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.follower_id
     *
     * @return the value of follow.follower_id
     *
     * @mbggenerated
     */
    public Integer getFollowerId() {
        return followerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.follower_id
     *
     * @param followerId the value for follow.follower_id
     *
     * @mbggenerated
     */
    public void setFollowerId(Integer followerId) {
        this.followerId = followerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.followed_user_id
     *
     * @return the value of follow.followed_user_id
     *
     * @mbggenerated
     */
    public Integer getFollowedUserId() {
        return followedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.followed_user_id
     *
     * @param followedUserId the value for follow.followed_user_id
     *
     * @mbggenerated
     */
    public void setFollowedUserId(Integer followedUserId) {
        this.followedUserId = followedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.created_at
     *
     * @return the value of follow.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.created_at
     *
     * @param createdAt the value for follow.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.updated_at
     *
     * @return the value of follow.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.updated_at
     *
     * @param updatedAt the value for follow.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}