package com.hygg.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table notification
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Notification implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.notification_id
     *
     * @mbggenerated
     */
    private Integer notificationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.target_type
     *
     * @mbggenerated
     */
    private Integer targetType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.target_id
     *
     * @mbggenerated
     */
    private Integer targetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.sender_id
     *
     * @mbggenerated
     */
    private Integer senderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.recipient_id
     *
     * @mbggenerated
     */
    private Integer recipientId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notification_id
     *
     * @return the value of notification.notification_id
     *
     * @mbggenerated
     */
    public Integer getNotificationId() {
        return notificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notification_id
     *
     * @param notificationId the value for notification.notification_id
     *
     * @mbggenerated
     */
    public void setNotificationId(Integer notificationId) {
        this.notificationId = notificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.create_date
     *
     * @return the value of notification.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.create_date
     *
     * @param createDate the value for notification.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.status
     *
     * @return the value of notification.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.status
     *
     * @param status the value for notification.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.target_type
     *
     * @return the value of notification.target_type
     *
     * @mbggenerated
     */
    public Integer getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.target_type
     *
     * @param targetType the value for notification.target_type
     *
     * @mbggenerated
     */
    public void setTargetType(Integer targetType) {
        this.targetType = targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.target_id
     *
     * @return the value of notification.target_id
     *
     * @mbggenerated
     */
    public Integer getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.target_id
     *
     * @param targetId the value for notification.target_id
     *
     * @mbggenerated
     */
    public void setTargetId(Integer targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.sender_id
     *
     * @return the value of notification.sender_id
     *
     * @mbggenerated
     */
    public Integer getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.sender_id
     *
     * @param senderId the value for notification.sender_id
     *
     * @mbggenerated
     */
    public void setSenderId(Integer senderId) {
        this.senderId = senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.recipient_id
     *
     * @return the value of notification.recipient_id
     *
     * @mbggenerated
     */
    public Integer getRecipientId() {
        return recipientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.recipient_id
     *
     * @param recipientId the value for notification.recipient_id
     *
     * @mbggenerated
     */
    public void setRecipientId(Integer recipientId) {
        this.recipientId = recipientId;
    }
}