package com.hygg.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table post_information
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class PostInformation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_information.post_id
     *
     * @mbggenerated
     */
    private Integer postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_information.item_name
     *
     * @mbggenerated
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_information.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_information.folder_url
     *
     * @mbggenerated
     */
    private String folderUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_information.contact
     *
     * @mbggenerated
     */
    private String contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_information.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_information.post_time
     *
     * @mbggenerated
     */
    private Date postTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_information.img_names
     *
     * @mbggenerated
     */
    private String imgNames;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_information.author_id
     *
     * @mbggenerated
     */
    private Integer authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_information.price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_information.tag
     *
     * @mbggenerated
     */
    private String tag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_information.post_id
     *
     * @return the value of post_information.post_id
     *
     * @mbggenerated
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_information.post_id
     *
     * @param postId the value for post_information.post_id
     *
     * @mbggenerated
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_information.item_name
     *
     * @return the value of post_information.item_name
     *
     * @mbggenerated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_information.item_name
     *
     * @param itemName the value for post_information.item_name
     *
     * @mbggenerated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_information.description
     *
     * @return the value of post_information.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_information.description
     *
     * @param description the value for post_information.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_information.folder_url
     *
     * @return the value of post_information.folder_url
     *
     * @mbggenerated
     */
    public String getFolderUrl() {
        return folderUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_information.folder_url
     *
     * @param folderUrl the value for post_information.folder_url
     *
     * @mbggenerated
     */
    public void setFolderUrl(String folderUrl) {
        this.folderUrl = folderUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_information.contact
     *
     * @return the value of post_information.contact
     *
     * @mbggenerated
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_information.contact
     *
     * @param contact the value for post_information.contact
     *
     * @mbggenerated
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_information.status
     *
     * @return the value of post_information.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_information.status
     *
     * @param status the value for post_information.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_information.post_time
     *
     * @return the value of post_information.post_time
     *
     * @mbggenerated
     */
    public Date getPostTime() {
        return postTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_information.post_time
     *
     * @param postTime the value for post_information.post_time
     *
     * @mbggenerated
     */
    public void setPostTime(Date postTime) {
        this.postTime = postTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_information.img_names
     *
     * @return the value of post_information.img_names
     *
     * @mbggenerated
     */
    public String getImgNames() {
        return imgNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_information.img_names
     *
     * @param imgNames the value for post_information.img_names
     *
     * @mbggenerated
     */
    public void setImgNames(String imgNames) {
        this.imgNames = imgNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_information.author_id
     *
     * @return the value of post_information.author_id
     *
     * @mbggenerated
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_information.author_id
     *
     * @param authorId the value for post_information.author_id
     *
     * @mbggenerated
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_information.price
     *
     * @return the value of post_information.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_information.price
     *
     * @param price the value for post_information.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_information.tag
     *
     * @return the value of post_information.tag
     *
     * @mbggenerated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_information.tag
     *
     * @param tag the value for post_information.tag
     *
     * @mbggenerated
     */
    public void setTag(String tag) {
        this.tag = tag;
    }
}