package com.hygg.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table post_information
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class PostInformation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_information.post_id
     *
     * @mbggenerated
     */
    private Integer postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_information.item_name
     *
     * @mbggenerated
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_information.folder_url
     *
     * @mbggenerated
     */
    private String folderUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_information.img_num
     *
     * @mbggenerated
     */
    private Integer imgNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_information.contact
     *
     * @mbggenerated
     */
    private String contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_information.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_information.post_time
     *
     * @mbggenerated
     */
    private Date postTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_information.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_information.post_id
     *
     * @return the value of post_information.post_id
     *
     * @mbggenerated
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_information.post_id
     *
     * @param postId the value for post_information.post_id
     *
     * @mbggenerated
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_information.item_name
     *
     * @return the value of post_information.item_name
     *
     * @mbggenerated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_information.item_name
     *
     * @param itemName the value for post_information.item_name
     *
     * @mbggenerated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_information.folder_url
     *
     * @return the value of post_information.folder_url
     *
     * @mbggenerated
     */
    public String getFolderUrl() {
        return folderUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_information.folder_url
     *
     * @param folderUrl the value for post_information.folder_url
     *
     * @mbggenerated
     */
    public void setFolderUrl(String folderUrl) {
        this.folderUrl = folderUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_information.img_num
     *
     * @return the value of post_information.img_num
     *
     * @mbggenerated
     */
    public Integer getImgNum() {
        return imgNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_information.img_num
     *
     * @param imgNum the value for post_information.img_num
     *
     * @mbggenerated
     */
    public void setImgNum(Integer imgNum) {
        this.imgNum = imgNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_information.contact
     *
     * @return the value of post_information.contact
     *
     * @mbggenerated
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_information.contact
     *
     * @param contact the value for post_information.contact
     *
     * @mbggenerated
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_information.status
     *
     * @return the value of post_information.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_information.status
     *
     * @param status the value for post_information.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_information.post_time
     *
     * @return the value of post_information.post_time
     *
     * @mbggenerated
     */
    public Date getPostTime() {
        return postTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_information.post_time
     *
     * @param postTime the value for post_information.post_time
     *
     * @mbggenerated
     */
    public void setPostTime(Date postTime) {
        this.postTime = postTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_information.description
     *
     * @return the value of post_information.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_information.description
     *
     * @param description the value for post_information.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }
}