spring:
  servlet:
    multipart:
      enabled: true
    max-file-size: 5242880
    max-request-size: 20MB
fileUpload:
  avatar:
    pathPattern: /static/avatars/**
    resourceLocation: /usr/local/pic/avatars/
server:
  port: 8081
myServer:
  address: 47.90.245.180
dubbo:
  application:
    name: avatarupload-provider1
  registry:
    address: zookeeper://47.90.245.180:2181
  protocol:
    name: dubbo
    port: 20880
  provider:
    timeout: 3

