fileUpload:
  avatar:
    pathPattern: /static/avatars/**
    resourceLocation: /usr/local/pic/avatars/
server:
  port: 8081
myServer:
  address: 47.90.245.180
dubbo:
  application:
    name: avatarupload-provider1-1.0.0a
  registry:
    address: zookeeper://47.90.245.180:2181
  protocol:
    name: hessian
    port: 20881
    server: jetty
  provider:
    timeout: 10000
    version: 1.0.0

